version: "3.8"

services:
    app:
        build: .
        container_name: laravel-fitcount-app
        restart: unless-stopped
        environment:
            - APP_ENV=production
            - APP_KEY=${APP_KEY}
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=${DB_DATABASE}
            - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
        volumes:
            - .:/var/www
        networks:
            - app-network
        depends_on:
            - db
        expose:
            - "9000" # Expose port 9000 untuk komunikasi dengan nginx, di dalam Docker

    db:
        image: mariadb:10.11-alpine
        container_name: laravel-fitcount-db
        restart: unless-stopped
        environment:
            MARIADB_DATABASE: ${DB_DATABASE}
            MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MARIADB_USER: ${DB_USERNAME}
            MARIADB_PASSWORD: ${DB_PASSWORD}
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    db_data:
        driver: local
