version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-fitcount-app
    restart: unless-stopped
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/node_modules
      - ./storage/app/public:/var/www/html/public/storage
    ports:
      - "80:80"
    networks:
      - fitcount-network
    depends_on:
      - db

  db:
    image: mariadb:10.11-alpine
    container_name: laravel-fitcount-db
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: laravel_fitcount
      MARIADB_ROOT_PASSWORD: root
      MARIADB_PASSWORD: password
      MARIADB_USER: fitcount
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - fitcount-network

networks:
  fitcount-network:
    driver: bridge

volumes:
  dbdata:
