version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - APP_KEY=base64:YourAppKeyHere
        depends_on:
            - db

    db:
        image: mysql:8.0-alpine
        container_name: mysql_db
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - "3306:3306"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: phpmyadmin
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        ports:
            - "8080:80"
        depends_on:
            - db

    nginx:
        image: nginx:alpine
        container_name: nginx_proxy
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./certbot:/etc/letsencrypt
            - .:/var/www/html
        depends_on:
            - app

    certbot:
        image: certbot/certbot
        container_name: certbot_auto
        volumes:
            - ./certbot:/etc/letsencrypt
            - ./certbot/www:/var/www/html
        command: certonly --webroot -w /var/www/html --force-renewal -d example.com -d www.example.com --email youremail@example.com --agree-tos --no-eff-email
        depends_on:
            - nginx

volumes:
    db_data:
